main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
   path('', views.home_page, name='list'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("service/", include("service.urls")),
    path("users/", include("users.urls")),
    path("", include("main.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from django.urls import path
from service import views
app_name = 'service'

urlpatterns = [
   path("settings/", views.SettingsListView.as_view()),
   path("settings/create/", views.SettingsCreateView.as_view()),
   path("settings/delete/<int:pk>/", views.SettingsDeleteView.as_view()),
   path("settings/update/<int:pk>/", views.SettingsUpdateView.as_view()),
   path("settings/<int:pk>/", views.SettingsDetailView.as_view(), name='settings'),
   path("message/", views.Message_to_SendListView.as_view()),
   path("message/create/", views.Message_to_SendCreateView.as_view()),
   path("message/delete/<int:pk>/", views.Message_to_SendDeleteView.as_view()),
   path("message/update/<int:pk>/", views.Message_to_SendUpdateView.as_view()),
   path("message/<int:pk>/", views.Message_to_SendDetailView.as_view(), name='message'),
   path("logs/", views.Mailing_LogsListView.as_view()),
   path("logs/create/", views.Mailing_LogsCreateView.as_view()),
   path("logs/delete/<int:pk>/", views.Mailing_LogsDeleteView.as_view()),
   path("logs/update/<int:pk>/", views.Mailing_LogsUpdateView.as_view()),
   path("logs/<int:pk>/", views.Mailing_LogsDetailView.as_view(), name='logs'),
]

service/models.py
from django.db import models
from users.models import User

NULLABLE = {'null':True, 'blank':True}

class Settings(models.Model):
    mailing_time_date = models.DateTimeField(verbose_name='Время рассылки')
    periodicity = models.CharField(max_length=100, verbose_name='Периодичность')
    mailing_status = models.CharField(max_length=100, verbose_name='Cтатус рассылки')
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name='settings')
   
    def __str__(self):
        return f'{self.mailing_time_date} {self.periodicity} {self.mailing_status}' 
   
    class Meta:
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'
        ordering = ('mailing_time_date',)

class Message_to_Send(models.Model):
    letter_subject = models.CharField(max_length=200, verbose_name='Тема письма')
    letter_body = models.TextField(verbose_name='Тело письма')
    settings = models.ForeignKey(Settings, on_delete=models.CASCADE, related_name='message_to_send')
   
    def __str__(self):
        return f'{self.letter_subject} {self.letter_body} {self.settings}' 
   
    class Meta:
        verbose_name = 'Cообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('letter_subject',)

class Mailing_Logs(models.Model):
    date_and_time_of_last_attempt = models.DateTimeField(verbose_name='Дата и время последней попытки')
    attempt_status = models.CharField(max_length=100, verbose_name='Статус попытки')
    mail_server_response = models.TextField(max_length=100, verbose_name='Ответ почтового сервера')
    settings = models.ForeignKey(Settings, on_delete=models.CASCADE, related_name='mailing_logs')
   
    def __str__(self):
        return f'{self.date_and_time_of_last_attempt} {self.attempt_status} {self.settings}' 
   
    class Meta:
        verbose_name = 'Журнал рассылок'
        verbose_name_plural = 'Журналы рассылок'
        ordering = ('date_and_time_of_last_attempt',)

service/views.py
from service.models import Settings, Message_to_Send, Mailing_Logs 
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from service.permissions import AuthorMessagePermissionsMixin, AuthorPermissionsMixin, ModeratorMessagePermissionsMixin, ModeratorPermissionsMixin
from users.models import User

@method_decorator(login_required, name='dispatch')
class SettingsCreateView(CreateView):
   model = Settings
   fields = ('mailing_time_date', 'periodicity', 'mailing_status', 'client')
   success_url = '/service/settings/'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs) 
      settings_objects = User.objects.all()
      context['objects'] = settings_objects
      return context

@method_decorator(login_required, name='dispatch')
class SettingsDeleteView(AuthorPermissionsMixin, DeleteView):
   model = Settings
   success_url = '/service/settings/' 
   
@method_decorator(login_required, name='dispatch')
class SettingsListView(ListView):
   model = Settings

@method_decorator(login_required, name='dispatch')
class SettingsDetailView(ModeratorPermissionsMixin, DetailView):
   model = Settings

@method_decorator(login_required, name='dispatch')
class SettingsUpdateView(ModeratorPermissionsMixin, UpdateView):
   model = Settings
   fields = ('mailing_time_date', 'periodicity', 'mailing_status', 'client')
   success_url = '/service/settings/'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      settings_objects = Settings.objects.all()
      context['objects'] = settings_objects
      context['user_options'] = User.objects.all()
      is_moder = self.request.user.groups.filter(name='moderator').exists()
      is_owner = self.get_object().client  == self.request.user
      while True:
         if is_owner:
            break
         
         elif is_moder:
            context['is_moderator'] = is_moder
            break
      return context
   
#--------------------------------------------------------------
@method_decorator(login_required, name='dispatch')
class Message_to_SendCreateView(CreateView):
   model = Message_to_Send
   fields = ('letter_subject', 'letter_body', 'settings')
   success_url = '/service/message/'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      settings_objects = Settings.objects.filter(client_id=self.request.user.id)
      context['objects'] = settings_objects
      return context
   
@method_decorator(login_required, name='dispatch')
class Message_to_SendDeleteView(AuthorMessagePermissionsMixin, DeleteView):
   model = Message_to_Send
   success_url = '/service/message/' 

@method_decorator(login_required, name='dispatch')
class Message_to_SendListView(ListView):
   model = Message_to_Send
   
@method_decorator(login_required, name='dispatch')
class Message_to_SendDetailView(AuthorMessagePermissionsMixin, DetailView):
   model = Message_to_Send

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['object'] = self.object
      settings = self.object.settings  # Получаем связанные настройки

      if settings.mailing_status == 'запущена':
         context['launched'] = settings.mailing_status
      elif settings.mailing_status == 'создана':
         context['can_start'] = settings.mailing_status 
      else:
         context['not_start'] = settings.mailing_status 
      return context

@method_decorator(login_required, name='dispatch')
class Message_to_SendUpdateView(AuthorMessagePermissionsMixin, UpdateView):
   model = Message_to_Send
   fields = ('letter_subject', 'letter_body', 'settings')
   success_url = '/service/message/'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      settings_objects = Settings.objects.filter(client_id=self.request.user.id)
      context['objects'] = settings_objects
      return context
   
#--------------------------------------------------------------
@method_decorator(login_required, name='dispatch')
class Mailing_LogsCreateView(ModeratorMessagePermissionsMixin, CreateView):
   model = Mailing_Logs
   fields = ('date_and_time_of_last_attempt', 'attempt_status', 'mail_server_response', 'settings')
   success_url = '/service/logs/'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      settings_objects = Settings.objects.all()
      context['objects'] = settings_objects
      return context

@method_decorator(login_required, name='dispatch')
class Mailing_LogsDeleteView(ModeratorMessagePermissionsMixin, DeleteView):
   model = Mailing_Logs
   success_url = '/service/logs/' 

@method_decorator(login_required, name='dispatch')
class Mailing_LogsListView(ListView):
   model = Mailing_Logs

@method_decorator(login_required, name='dispatch')
class Mailing_LogsDetailView(ModeratorMessagePermissionsMixin, DetailView):
   model = Mailing_Logs

@method_decorator(login_required, name='dispatch')
class Mailing_LogsUpdateView(ModeratorMessagePermissionsMixin, UpdateView):
   model = Mailing_Logs
   fields = ('date_and_time_of_last_attempt', 'attempt_status', 'mail_server_response', 'settings')
   success_url = '/service/logs/'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      settings_objects = Settings.objects.all()
      context['objects'] = settings_objects
      return context

service/templates/service/access_denied.html
<!DOCTYPE html>
<html>
<head>
    <title>Доступ запрещен</title>
</head>
<body>
    <h1>Доступ запрещен</h1>
    <p>У вас нет прав для выполнения этого действия.</p>
</body>
</html>

service/templates/service/customer_service_form.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">
  </head>
  <style>
    .rewd {
      color: red; 
      font-weight: bold; 
    }
    </style>
  <body class="text-center">
    <form class="form-signin" method="POST">
      {% csrf_token %}
       {% if form.errors %}
      <div class="red">
        <ul>
          {% for field_name, errors in form.errors.items %}
            {% for error in errors %}
              <li class="rewd">{{ error }}</li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}
      <h1 class="h3 mb-3 font-weight-normal">Пожалуйста зарегистрируйтесь</h1>
      
         <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Почта" required autofocus>
         <input type="password" name="password"  id="inputPassword" class="form-control" placeholder="Пароль" required>
         <input type="name" name="last_name"  class="form-control" placeholder="Имя" required autofocus>
         <input type="name" name="first_name" class="form-control" placeholder="Фамилия" required>   
      <div class="checkbox mb-3">
        <label>
            уже есть аккаунт? <a href="{% url 'login' %}">Войдите</a>
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Отправить</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2023</p>
    </form>
  </body>
</html>

service/templates/service/mailing_logs_confirm_delete.html
{% extends 'service/base.html' %} 
{% block content %} 

<div class="col-12">
   <div class="row">
      <div class="col-6">
         <div class="card">
            <div class="card-body">
               <form method="post">
                  {% csrf_token %}
                  <p>Хотите удалить клиента?: {{ object }}</p>
                  <button type="submit" class="btn btn-danger">Подтвердить</button>
                  <a href="/service/logs" class="btn btn-warning">Отмена</a>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>

{% endblock %}    

service/templates/service/mailing_logs_detail.html
{% extends 'service/base.html' %}     
{% block content %}       
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Дата и время последней попытки: <br> {{object.date_and_time_of_last_attempt}}</p> 
                  <p class="card-text">Статус попытки: {{object.attempt_status}}</p>
                  <p class="card-text">Ответ почтового сервера: {{object.mail_server_response}}</p>
                  <p class="card-text">settings: {{object.settings}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href='/service/logs/update/{{ object.pk }}'">Edit</button>
                      <button type="button" class="btn btn-danger" onclick="window.location.href='/service/logs/delete/{{ object.pk }}'">Delete</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
{% endblock %}

service/templates/service/mailing_logs_form.html
{% extends 'service/base.html' %} 
{% block content %} 
<form method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <div class="form-group has-success">
     <label class="control-label" for="inputSuccess1">Дата и время последней попытки</label>
     <input type="datetime-local" name="date_and_time_of_last_attempt" class="form-control" id="inputSuccess1">
   </div>
   <div class="form-group has-error">
     <label class="control-label" for="inputError1">Статус попытки</label>
     <input type="name" name="attempt_status" class="form-control" id="inputError1">
   </div>
   <div class="form-group has-error">
    <label class="control-label" for="inputError1">Ответ почтового сервера</label>
    <input type="name" name="mail_server_response" class="form-control" id="inputError1">
  </div>
  <div class="form-group has-success">
    <label class="required" for="id_client">Настройки:</label>
    <div class="related-widget-wrapper" data-model-ref="Клиент сервиса">
        <select name="settings" required="" id="id_client">
            <option value="" selected>----------------------------------------------------</option>
            {% for obj in objects %}
                <option value="{{ obj.pk }}">{{ obj }}</option>
            {% endfor %}
        </select>
    </div>
</div>
   <div class="form-group has-error">
      <label class="control-label" for="inputError1"></label>
      <input type="submit" class="btn btn-primary" id="inputError1">
 </form>
{% endblock %} 

service/templates/service/mailing_logs_list.html
{% extends 'service/base.html' %}     
{% block content %}
  
<input onclick="window.location.href='/service/logs/create'" class="btn btn-success mb-4" type="submit" value="Добавить журнал" id="add-article-btn" style="position: absolute; top: 28%; left: 18.3%;">
   
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Дата и время последней попытки: <br>{{object.date_and_time_of_last_attempt}}</p>
                  <p class="card-text">Статус попытки: {{object.attempt_status}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button onclick="window.location.href='/service/logs/{{object.pk}}'" type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button onclick="window.location.href='/service/logs/update/{{object.pk}}'" type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                      <button onclick="window.location.href='/service/logs/delete/{{object.pk}}'" type="button" class="btn btn-danger">Delete</button>
                    </div>
                  </div>
                </div>
              </div>
              <style>
                .btn{
                   float: left;
                }
                .card-body  {
                   
                   height:230px;
                }
             </style>
            </div>
            {% endfor %}
{% endblock %}

service/templates/service/message_to_send_confirm_delete.html
{% extends 'service/base.html' %} 
{% block content %} 

<div class="col-12">
   <div class="row">
      <div class="col-6">
         <div class="card">
            <div class="card-body">
               <form method="post">
                  {% csrf_token %}
                  <p>Хотите удалить клиента?: {{ object }}</p>
                  <button type="submit" class="btn btn-danger">Подтвердить</button>
                  <a href="/service/message" class="btn btn-warning">Отмена</a>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>

{% endblock %}    

service/templates/service/message_to_send_detail.html
{% extends 'service/base.html' %}     
{% block content %}       
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Тема письма: {{object.letter_subject}}</p> 
                  <p class="card-text">Тело письма: {{object.letter_body}}</p>
                  <p class="card-text">settings: {{object.settings}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href='/service/message/update/{{ object.pk }}'">Edit</button>
                      <button type="button" class="btn btn-danger" onclick="window.location.href='/service/message/delete/{{ object.pk }}'">Delete</button>
                    </div>
                    {% if can_start %}
                      <button type="button" class="btn btn-success mb-9" onclick="window.location.href='/service/create_dispatch/'">Запустить</button>
                    {% elif not_start %}
                      <button type="button" class="btn btn-success mb-9" disabled>Завершилось</button>
                    {% elif launched %}
                      <button type="button" class="btn btn-success mb-9" disabled>Запущено</button>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
{% endblock %}

service/templates/service/message_to_send_form.html
{% extends 'service/base.html' %} 
{% block content %} 
<form method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <div class="form-group has-success">
     <label class="control-label" for="inputSuccess1">Тема письма</label>
     <input type="name" name="letter_subject" class="form-control" id="inputSuccess1">
   </div>
   <div class="form-group has-error">
     <label class="control-label" for="inputError1">Тело письма</label>
     <input type="text" name="letter_body" class="form-control" id="inputError1">
   </div>
   <div class="form-group has-success">
      <label class="required" for="id_client">Настройки:</label>
      <div class="related-widget-wrapper" data-model-ref="Клиент сервиса">
          <select name="settings" required="" id="id_client">
              <option value="" selected>----------------------------------------------------</option>
              {% for settings in objects %}
                <option value="{{ settings.pk }}">{{ settings }}</option>
              {% endfor %}
          </select>
      </div>
   </div>
   <div class="form-group has-error">
      <label class="control-label" for="inputError1"></label>
      <input type="submit" class="btn btn-primary" id="inputError1">
 </form>
{% endblock %} 

service/templates/service/message_to_send_list.html
{% extends 'service/base.html' %}     
{% block content %}
  
<input onclick="window.location.href='/service/message/create'" class="btn btn-success mb-4" type="submit" value="Добавить сообщение" id="add-article-btn" style="position: absolute; top: 28%; left: 18.3%;">
   
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Тема письма: {{object.letter_subject}}</p>
                  <p class="card-text">Тело письма: {{object.letter_body}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button onclick="window.location.href='/service/message/{{object.pk}}'" type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button onclick="window.location.href='/service/message/update/{{object.pk}}'" type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                      <button onclick="window.location.href='/service/message/delete/{{object.pk}}'" type="button" class="btn btn-danger">Delete</button>
                    </div>
                  </div>
                </div>
              </div>
              <style>
                .btn{
                   float: left;
                }
                .card-body  {
                   
                   height:230px;
                }
             </style>
            </div>
            {% endfor %}
{% endblock %}

service/templates/service/settings_confirm_delete.html
{% extends 'service/base.html' %} 
{% block content %} 

<div class="col-12">
   <div class="row">
      <div class="col-6">
         <div class="card">
            <div class="card-body">
               <form method="post">
                  {% csrf_token %}
                  <p>Хотите удалить настройку?: {{ object }}</p>
                  <button type="submit" class="btn btn-danger">Подтвердить</button>
                  <a href="/service/settings" class="btn btn-warning">Отмена</a>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>

{% endblock %}    

service/templates/service/settings_detail.html
{% extends 'service/base.html' %}     
{% block content %}       
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Время рассылки: {{object.mailing_time_date}}</p> 
                  <p class="card-text">Периодичность: {{object.periodicity}}</p>
                  <p class="card-text">Cтатус рассылки: {{object.mailing_status}}</p>
                  <p class="card-text">Клиент: {{object.client}}</p> 
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href='/service/settings/update/{{ object.pk }}'">Edit</button>
                      <button type="button" class="btn btn-danger" onclick="window.location.href='/service/settings/delete/{{ object.pk }}'">Delete</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
{% endblock %}

service/templates/service/settings_form.html
{% extends 'service/base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if is_moderator %}
        <div class="form-group has-success">
            <label class="control-label" for="inputSuccess1">Время рассылки</label>
            <input type="time" name="mailing_time_date" value='{{ object.mailing_time_date }}' class="form-control" id="inputSuccess1" readonly>
        </div>

        <label class="control-label" for="periodicitySelect">Выберите Периодичность</label>
        <input type="name" name="periodicity" value='{{ object.periodicity }}' class="form-control" id="inputSuccess1" readonly>

        <br>

        <label class="control-label" for="statusSelect">Cтатус рассылки</label>
        <select id="periodicitySelect" name="mailing_status">
            <option value="завершена" {% if object.mailing_status == "завершена" %}selected{% endif %}>завершена</option>
            <option value="создана" {% if object.mailing_status == "создана" %}selected{% endif %}>создана</option>
            <option value="запущена" {% if object.mailing_status == "запущена" %}selected{% endif %}>запущена</option>
        </select>

        <div class="form-group has-success">
            <label class="required" for="id_client">Клиент:</label>
            <div class="related-widget-wrapper" data-model-ref="Клиент сервиса">
                <select name="client" required="" id="id_client">
                    {% for user_option in user_options %}
                        {% if user_option.pk == settings.client.pk %}
                            <option value="{{ user_option.pk }}" selected>{{ user_option }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        
    {% else %}
        <div class="form-group has-success">
            <label class="control-label" for="inputSuccess1">Время рассылки</label>
            <input type="time" name="mailing_time_date" value='{{ object.mailing_time_date }}' class="form-control" id="inputSuccess1">
        </div>

        <label class="control-label" for="periodicitySelect">Выберите Периодичность</label>
        <select id="periodicitySelect" name="periodicity">
            <option value="раз в день" {% if object.periodicity == "раз в день" %}selected{% endif %}>раз в день</option>
            <option value="раз в неделю" {% if object.periodicity == "раз в неделю" %}selected{% endif %}>раз в неделю</option>
            <option value="раз в месяц" {% if object.periodicity == "раз в месяц" %}selected{% endif %}>раз в месяц</option>
        </select>
        

        <br>

        <label class="control-label" for="statusSelect">Cтатус рассылки</label>
        <select id="periodicitySelect" name="mailing_status">
            <option value="завершена" {% if object.mailing_status == "завершена" %}selected{% endif %}>завершена</option>
            <option value="создана" {% if object.mailing_status == "создана" %}selected{% endif %}>создана</option>
            <option value="запущена" {% if object.mailing_status == "запущена" %}selected{% endif %}>запущена</option>
        </select>

        <div class="form-group has-success">
            <label class="required" for="id_client">Клиент:</label>
            <div class="related-widget-wrapper" data-model-ref="Клиент сервиса">
                <select name="client" required="" id="id_client">
                    <option value="{{ user.pk }}" selected>{{ user }}</option>
                </select>
            </div>
        </div>
    {% endif %}

    <div class="form-group has-error">
        <label class="control-label" for="inputError1"></label>
        <input type="submit" class="btn btn-primary" value="Создать настройки">
    </div>
</form>
{% endblock %}

service/templates/service/settings_list.html
{% extends 'service/base.html' %}     
{% block content %}
  
<input onclick="window.location.href='/service/settings/create'" class="btn btn-success mb-4" type="submit" value="Добавить настройку" id="add-article-btn" style="position: absolute; top: 28%; left: 18.3%;">
   
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Время рассылки: {{object.mailing_time_date}}</p>
                  <p class="card-text">Периодичность: {{object.periodicity}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button onclick="window.location.href='/service/settings/{{object.pk}}'" type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button onclick="window.location.href='/service/settings/update/{{object.pk}}'" type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                      <button onclick="window.location.href='/service/settings/delete/{{object.pk}}'" type="button" class="btn btn-danger">Delete</button>
                    </div>
                  </div>
                </div>
              </div>
              <style>
                .btn{
                   float: left;
                }
                .card-body  {
                   
                   height:230px;
                }
             </style>
            </div>
            {% endfor %}
{% endblock %}